import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Download, Share2, FileText, FileSpreadsheet, FileCode } from "lucide-react";

const RECENT_REPORTS = [
  {
    name: "Q1 Portfolio Summary",
    type: "Portfolio Summary",
    date: "Mar 15, 2025",
    user: { name: "Sarah Chen", avatar: "", initials: "SC" },
    projects: "All (12)",
    format: "pdf",
    size: "4.2 MB",
  },
  {
    name: "Meridian Budget Analysis",
    type: "Budget Variance",
    date: "Mar 14, 2025",
    user: { name: "Alex Rivet", avatar: "", initials: "AR" },
    projects: "Meridian Quarter",
    format: "excel",
    size: "1.8 MB",
  },
  {
    name: "Lender Compliance - West",
    type: "Compliance",
    date: "Mar 12, 2025",
    user: { name: "Sarah Chen", avatar: "", initials: "SC" },
    projects: "Skyline, River North",
    format: "pdf",
    size: "2.5 MB",
  },
  {
    name: "Investor Update - Mar",
    type: "Investor Report",
    date: "Mar 10, 2025",
    user: { name: "James Wilson", avatar: "", initials: "JW" },
    projects: "Portfolio",
    format: "pdf",
    size: "3.1 MB",
  },
  {
    name: "Health Scorecard - Weekly",
    type: "Project Health",
    date: "Mar 08, 2025",
    user: { name: "Sarah Chen", avatar: "", initials: "SC" },
    projects: "All (12)",
    format: "pdf",
    size: "1.2 MB",
  },
  {
    name: "Cash Flow Projections",
    type: "Financial Forecast",
    date: "Mar 05, 2025",
    user: { name: "Alex Rivet", avatar: "", initials: "AR" },
    projects: "All (12)",
    format: "excel",
    size: "0.9 MB",
  },
  {
    name: "Development Update Q1",
    type: "Progress Report",
    date: "Mar 02, 2025",
    user: { name: "James Wilson", avatar: "", initials: "JW" },
    projects: "Harbor Wharf",
    format: "word",
    size: "5.4 MB",
  },
  {
    name: "Variance Narrative",
    type: "Narrative Analysis",
    date: "Feb 28, 2025",
    user: { name: "Sarah Chen", avatar: "", initials: "SC" },
    projects: "River North",
    format: "pdf",
    size: "1.5 MB",
  },
];

const FormatIcon = ({ format }: { format: string }) => {
  switch (format) {
    case "pdf": return <FileText className="w-4 h-4 text-red-500" />;
    case "excel": return <FileSpreadsheet className="w-4 h-4 text-green-600" />;
    case "word": return <FileCode className="w-4 h-4 text-blue-500" />;
    default: return <FileText className="w-4 h-4 text-muted-foreground" />;
  }
};

export function RecentReportsLibrary() {
  return (
    <Card className="border-border">
      <CardHeader className="flex flex-row items-center justify-between">
        <CardTitle className="text-lg">Generated Reports</CardTitle>
        <Button variant="outline" size="sm">View Library</Button>
      </CardHeader>
      <CardContent>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Report Name</TableHead>
              <TableHead>Type</TableHead>
              <TableHead>Date</TableHead>
              <TableHead>Generated By</TableHead>
              <TableHead>Projects</TableHead>
              <TableHead>Format</TableHead>
              <TableHead className="text-right">Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {RECENT_REPORTS.map((report, index) => (
              <TableRow key={index} className="group">
                <TableCell>
                  <div className="font-medium text-sm">{report.name}</div>
                  <div className="text-[10px] text-muted-foreground">{report.size}</div>
                </TableCell>
                <TableCell>
                  <Badge variant="secondary" className="text-[10px] font-normal">{report.type}</Badge>
                </TableCell>
                <TableCell className="text-sm">{report.date}</TableCell>
                <TableCell>
                  <div className="flex items-center gap-2">
                    <Avatar className="h-6 w-6">
                      <AvatarImage src="" />
                      <AvatarFallback className="text-[10px] bg-primary/10 text-primary">{report.user.initials}</AvatarFallback>
                    </Avatar>
                    <span className="text-xs">{report.user.name}</span>
                  </div>
                </TableCell>
                <TableCell className="text-xs text-muted-foreground">{report.projects}</TableCell>
                <TableCell>
                  <div className="flex items-center gap-1.5 uppercase text-[10px] font-bold text-muted-foreground">
                    <FormatIcon format={report.format} />
                    {report.format}
                  </div>
                </TableCell>
                <TableCell className="text-right">
                  <div className="flex justify-end gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                    <Button variant="ghost" size="icon" className="h-8 w-8" title="Download">
                      <Download className="h-4 w-4" />
                    </Button>
                    <Button variant="ghost" size="icon" className="h-8 w-8" title="Share">
                      <Share2 className="h-4 w-4" />
                    </Button>
                  </div>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </CardContent>
    </Card>
  );
}